[build]
  publish = "./"
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/add-catch"
  to = "/add-catch.html"
  status = 200

[[redirects]]
  from = "/catches"
  to = "/catches.html"
  status = 200
